title: NZD-SOS
subtitle: New Zealand Doctors Speaking Out with actual Science
summary: Reminding the anti-vaxxers of the importance of science. Standing up for our safety, those of our families, our patients and the general public.
description: This is a parody site.
url: https://nzd-sos.com
permalink: /:title
remote_theme: jonaharagon/jekyll-bootstrap-theme
timezone: Pacific/Auckland
author:
  name: Mark Honeychurch
  email: mark@honeychurch.org
bootstrap:
  header_pages:
    - index.md
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
